targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - core/**.dart
      - test/**.dart
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        generate_for:
            - lib/**.codegen.dart
            - core/**.codegen.dart
        options:
          field_rename: snake
      freezed:freezed:
        options:
          make_collections_unmodifiable: false
        generate_for:
            - lib/**/bloc/**.dart
            - lib/**/cubit/**.dart
            - lib/**.codegen.dart
            - core/**.codegen.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/injector.dart
