name: salt_flutter_mini_project
description: A new Flutter project.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_route: 5.0.4
  bloc_concurrency: ^0.2.2
  build_runner_core: 7.2.7+1
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  freezed_annotation: 2.2.0
  get_it: ^7.2.0
  image_picker: ^1.0.2
  injectable: ^1.5.2
  intl: ^0.18.0
  json_annotation: 4.7.0
  lazy_load_scrollview: ^1.3.0
  loading_animation_widget: ^1.2.0+4
  path: ^1.8.1
  path_provider: ^2.0.15
  responsive_builder: ^0.7.0
  responsive_framework: ^0.1.9
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  shimmer: ^3.0.0
  sqflite: ^2.2.6
  sqflite_common_ffi: null

dev_dependencies:
  auto_route_generator: 5.0.2
  build_runner: ^2.4.6
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.2.0
  injectable_generator: 1.5.4
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans.ttf
  assets:
    - assets/svgs/
    - assets/svgs/icons/
    - assets/images/
